# LabManager 打包脚本
import PyInstaller.__main__

PyInstaller.__main__.run([
    "src/admin.py",
    "--name=LabManager-V3.2",
    "--onefile",
    "--windowed",
    "--noconsole",
    "--add-data=templates;templates",
    "--add-data=static;static",
    "--add-data=src;src",
    "--hidden-import=flask",
    "--hidden-import=flask_sqlalchemy",
    "--hidden-import=flask_login",
    "--hidden-import=flask_wtf",
    "--hidden-import=waitress",
    "--hidden-import=werkzeug",
    "--hidden-import=jinja2",
    "--hidden-import=sqlalchemy",
    "--hidden-import=wtforms",
    "--hidden-import=tkinter",
    "--hidden-import=psutil",
    "--hidden-import=pystray",
    "--hidden-import=PIL",
    "--hidden-import=PIL.Image",
    "--hidden-import=PIL.ImageDraw",
    "--collect-all=flask",
    "--collect-all=flask_sqlalchemy",
    "--collect-all=flask_login",
    "--collect-all=flask_wtf",
    "--collect-all=waitress",
    "--collect-all=pystray",
])
